-- AlterTable
ALTER TABLE "Tag" ADD COLUMN "engMax" REAL;
ALTER TABLE "Tag" ADD COLUMN "engMin" REAL;
ALTER TABLE "Tag" ADD COLUMN "formula" TEXT;
ALTER TABLE "Tag" ADD COLUMN "rawMax" REAL;
ALTER TABLE "Tag" ADD COLUMN "rawMin" REAL;
ALTER TABLE "Tag" ADD COLUMN "unit" TEXT;
